### ISSUE TITLE
Osb.exe not responding

### ISSUE THREAD

**Issue by harwinroche** [baffler/OBS-OpenVR-Input-Plugin#1]
After adding the plugin Osb.exe not responding when openvr capture option is selected
![34](https://user-images.githubusercontent.com/11989673/40420307-ad5ce004-5ea5-11e8-81fd-ed7b6214c225.png)

**Comment by baffler** [comment]
Can you make sure openvr_api.dll exists in your plugins directory? If it does exist, could you please upload your recent crash log. Go into OBS and click File -> Show Settings Folder, then click on crashes folder and the crash logs will be in there.

**Comment by harwinroche** [comment]
Hi Baffler.
openvr_api.dll  is available in plugins directory. Crash logs was empty but was able to find log file will this be of any help.
![34](https://user-images.githubusercontent.com/11989673/40616987-8361fb32-62aa-11e8-9804-16ad9d62ba2d.png)
[2018-05-28 18-51-52.txt](https://github.com/baffler/OBS-OpenVR-Input-Plugin/files/2045259/2018-05-28.18-51-52.txt)

**Comment by baffler** [comment]
Looking through your logs I did notice this:
`Failed to load 'en-US' text for module: 'win-openvr.dll`
In the zip file for the plugin there is a "data" folder, you'll need to extract that as well into:
`D:\obs-studio`
It's crashing because it can't load those locale files. However, it shouldn't crash because of that, and that's something I can fix. Possibly an error message or something should appear. That will be something I can fix, but for now you can just make sure those files are extracted there, 

The "en-US.ini" should exist in:
`D:\obs-studio\data\obs-plugins\win-openvr\locale`

And also the "win-openvr-presets.ini" should be in:
`D:\obs-studio\data\obs-plugins\win-openvr`

**Comment by harwinroche** [comment]
Hi Baffler,

Thanks!!! extracted and added the said files and working fine now.
![open vr](https://user-images.githubusercontent.com/11989673/40660089-ae0cc010-636d-11e8-85bd-79c54907a2f1.png)

**Comment by baffler** [comment]
With v1.11, this will no longer crash if the preset file doesn't exist. It simply won't load any presets but the plugin will function normally and allow you to do custom cropping.
