### ISSUE TITLE
duplicate prests

### ISSUE THREAD

**Issue by yibbayabbba** [baffler/OBS-OpenVR-Input-Plugin#14]
Hi, i just installed this and its works ok but evry time i go into the properties it duplicates the presets, so if you go into properties 3 times you have 3 times as many presets all duplicated

it also resets to default when going into properties and doesn't show what current settings you have

**Comment by baffler** [comment]
Can you go to [releases](https://github.com/baffler/OBS-OpenVR-Input-Plugin/releases) and download the latest version (v1.2). The presets duplicating was fixed in the latest version so it shouldn't happen. I'm also not having an issue with current settings disappearing, are you using OBS or Streamlabs OBS?

**Comment by yibbayabbba** [comment]
ok, i googled the plugin and the obs forum linked to 1.1, i'll try 1.2, thank you

im using obs

**Comment by baffler** [comment]
I just released [v1.3](https://github.com/baffler/OBS-OpenVR-Input-Plugin/releases/tag/v1.3) which fixes a couple other things if you wanna give it a try.

**Comment by yibbayabbba** [comment]
thanks, 1.3 only has source codes to download though

**Comment by baffler** [comment]
@yibbayabbba oops yea, fixed it!
