### ISSUE TITLE
Closing SteamVR will also force OBS to be closed

### ISSUE THREAD

**Issue by baffler** [baffler/OBS-OpenVR-Input-Plugin#3]
SteamVR seems to force kill any program that has used openvr api, including OBS.  Typically it would just close the VR game which makes sense, but since this plugin uses the openvr api, OBS gets closed as well.

Right now the plugin attempts to use ` vr::VR_Shutdown()` as well as `vr::VRSystem()->AcknowledgeQuit_UserPrompt()` when there is a `vr::VREvent_Quit` event, but it doesn't always prevent OBS from being force killed.

**Comment by BOLL7708** [comment]
I've made a number of C# applications that connect to OpenVR and I register them as `EVRApplicationType.VRApplication_Background` which indeed has them terminate whenever SteamVR shuts down. The different types are listed in the header file [here](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L1160). I have to confess I have not tried many of the other modes, and I just tried the "Other" one and it also quit with SteamVR... my guess is that changing this won't help much 🤔

-----
I did some testing and found a repeatable pattern, this as I've not bumped into OBS actually shutting in that often myself, and I know why now.
- Start SteamVR, then OBS, close SteamVR = OBS sticks around
- Start OBS, then SteamVR, close SteamVR = OBS also dies

I've had streams where I've restated SteamVR, luckily I have only had to do it once as doing it twice actually kills OBS now because then SteamVR was started after OBS.

-----
If I did the reverse test there is a different result, someting that I've been working around for a while now. This is also repeatable.
- Start SteamVR, then OBS, close OBS = OBS crashes
- Start OBS, then SteamVR, close OBS = OBS does not crash

In the same way here, if I close OBS successfully and start it again, it will crash when I close it again if SteamVR is still running. How I've worked around this is to always hide my OpenVR Input source before shutting OBS down, then it does not crash.

Maybe this is a clue to something... ? If needed I have plenty of crash logs for this last thing, 62 in total 😂 stretching from December 2017 to just now.

**Comment by baffler** [comment]
Are you sure it's crashing? I wouldn't mind seeing the crash logs because I wasn't able to produce an actual crash with it. I'm running OBS in debug mode with visual studio while SteamVR is force closing OBS and there's no debug info on an actual crash. However, I made need to do further testing because I didn't try all the scenarios you listed there.

**Comment by BOLL7708** [comment]
Here's one that happened today, it was when I was closing OBS without hiding the input.
[Crash 2018-06-05 23-42-41.txt](https://github.com/baffler/OBS-OpenVR-Input-Plugin/files/2074196/Crash.2018-06-05.23-42-41.txt)

**Comment by BOLL7708** [comment]
As a side note I bumped into an [open issue](https://github.com/ValveSoftware/openvr/issues/878) for OpenVR that was fairly similar to this. 

In my own application I do what you describe up top, I listen for the quit event and act on it. I don't run the user prompt acknowledge though, but `AcknowledgeQuit_Exiting();`, not sure if that's important. I let all my work finish, anything that talks to OpenVR, and then I do `OpenVR.Shutdown();` and my application survives. If I don't wait for the work to finish I get NPE's inside OpenVR.

I'm not very deep into testing yet so perhaps it's not bullet proof, just figured I would mention it here.

**Comment by BOLL7708** [comment]
I finally took at look at the code, I'm not a C++ developer, but I see that it is running what I would expect. `Acknowledge` and then later `Shutdown` through `win_openvr_deinit()`. Setting the flag that it's not initialized fairly immediately. 🤔 

Yeah, I don't know. If I switch between UserPrompt and Exiting in my own C# application it does no difference, it works deiniting regardless and I'm also using a flag to interrupt what I'm doing in my worker thread, so seems like this difference hardly matters.

One thing I did notice though. In `win_openvr_tick` only [one event](https://github.com/baffler/OBS-OpenVR-Input-Plugin/blob/master/plugins/win-openvr/win-openvr.cpp#L348) is grabbed to per cycle. We can actually poll this until it returns no result, to pull all the queued events out, this way we could react to the shutdown event earlier. SteamVR can spam quite a few events so might be worth trying.

**Comment by BOLL7708** [comment]
@baffler As I'm setting up OBS on a new PC I thought of this again 😋 Have you tried any of my suggestions? If not, I might try and set up a build environment over here, but again I've only done C# in Visual Studio so not 100% of how to proceed 😅

**Comment by baffler** [comment]
@BOLL7708 I'm not actually able to recreate the issue anymore. I haven't actually changed anything. Commenting out the AcknowledgeQuit function seems to make no difference, but when commenting the function to deinit, that's the only time I can get the issue to show up now so that OBS closes with SteamVR. I tried it in a lot of ways like SteamVR open first, then OBS, or OBS open first then open SteamVR. As well as opening OBS with SteamVR then closing OBS first, which still gives me a crash.

Exception thrown at 0x00007FF861ACB735 (vrclient_x64.dll) in obs64.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

It's from Polling the next event that causes the unhandled exception. Not sure how to fix this though, try/catch doesn't help at all.

Do you still get the issue with OBS closing with SteamVR? Maybe some bug was fixed with SteamVR?

**Comment by BOLL7708** [comment]
Oh yeah. crashing still happens. Right now I was removing a hidden OpenVR source with a visible still running, that also crashed the client. If I start the client after SteamVR and then close it with a visible OpenVR source, it crashes. This is a freshly installed system with latest OBS and plugin 😋

`AcknowledgeQuit` should still be run, or OpenVR will terminate the application for you, or so I've been told. Just that after acknowledging we should shutdown the connection to OpenVR as quickly as possible using `VR_Shutdown`. To hasten this up we should read all events ASAP, as I mentioned before it seems like one event is read per loop right now, this while we can read all available events each iteration.

Again I'm unfamiliar with setting up a build environment for C++ but I can imagine something like this could plausibly improve the situation. It's just a guess and hope though 😅

[Line 384 in win-openvr.cpp](https://github.com/baffler/OBS-OpenVR-Input-Plugin/blob/master/plugins/win-openvr/win-openvr.cpp#L348)
```
while (vr::VRSystem()->PollNextEvent(&e, sizeof(vr::VREvent_t))) // Will return false when out of events
{
	if (e.eventType == vr::VREvent_Quit)
	{
		vr::VRSystem()->AcknowledgeQuit_Exiting(); // We're not doing a user prompt anyway
		// Without this SteamVR will kill OBS process when it exits
		// TODO: OBS process will still be killed in some cases by SteamVR
		win_openvr_deinit(data);
	}
}
```

**Comment by BOLL7708** [comment]
Got back from my holiday and saw there was an update 😁 I no longer have to hide the source every time I shut OBS down, nice! Been trying to provoke the old crash, not happening! 😃

**Comment by ragesaq** [comment]
This still crashes my OBS when quitting SteamVR.

**Comment by baffler** [comment]
> This still crashes my OBS when quitting SteamVR.

Can you try [v1.4](https://github.com/baffler/OBS-OpenVR-Input-Plugin/releases/tag/v1.4) and let me know if you still get a crash? Thanks.

**Comment by ragesaq** [comment]
1.4 seems better, thanks!
