### ISSUE TITLE
Vive Cosmos Frame issues

### ISSUE THREAD

**Issue by Spektreplays** [baffler/OBS-OpenVR-Input-Plugin#30]
Ive been trying to go through everything and for some reason my frames are terrible with the plugin, i have a very solid computer build but for some reason the plugin causes terrible issues with frames on SLOBS.

**Comment by baffler** [comment]
Possibly related to issue #26. Is the framerate still really bad with the VR Display Mirror in SteamVR? This appears to be some SteamVR bug that would need to be fixed by them.

**Comment by Spektreplays** [comment]
I dont even use the display mirror, is there some way to disable it

**Comment by baffler** [comment]
![image](https://user-images.githubusercontent.com/1980600/83205727-5cb96980-a11d-11ea-8246-ae7f5958cad0.png)

I was asking if the display mirror had low FPS as well since this seems to be a SteamVR bug I believe the display mirror will have the same issue. If for some reason it doesn't, you can always do a game capture on the display mirror itself.

**Comment by Spektreplays** [comment]
The display mirror is unfortunately also low fps as shit.

**Comment by baffler** [comment]
Yea that's the same issue as #26. You can read through that to get an idea of what's going on. Seems you can revert to an older SteamVR release but there's a bit of a process to it. Hopefully Steam can get a fix out soon for the issue.
